### ISSUE TITLE
authorization-service will not deny authorization

### ISSUE THREAD

**Issue by reggersusa** [matik12/aurelia-permission#1]
I have just wired up aurelia-permission in the basic setup as described in the read.me. I am able to debug and see the authorization-service is being invoked, and I can see the correct permissions are being accessed for the sample user. I see this on routing as well as when I have a permission="only: ..." property on an element.
    But authorization is always given. No routes are redirected and elements I expect to be hidden are always displayed. I am not yet able to fully debug TypeScript, so it is not possible to single step, examine all variables and properly analyze the failure.
    I guess my question is how can I work with a pure Javascript version of this code to understand the flow? I am using gulp for builds. Having source maps for the TypeScript might be all I need.

**Comment by matik12** [comment]
Hi @reggersusa,

thanks for using this plugin. Can you share your plugin configuration and sample usage to see what you are trying to do? 

I just checked my sample plugin usage and it is still working like a harm, so I am not sure what troubles you are experiencing. Sample configuration:
```js
const UserPermission = {
  AddUsers: 'Add_Users',
  DeleteUsers: 'Delete_Users',
  ListUsers: 'List_Users',
}

const sampleUser = {
  id: 1,
  permissions: [
    UserPermission.AddUsers
    //, UserPermission.DeleteUsers 
    //, UserPermission.ListUsers // This means that current user does not have list users permission
  ]
}

const userPromise = new Promise(resolve => {
  // Simulate promise getting user data including permissions from API
  setTimeout(() => resolve(sampleUser), 100);
});

export function configure(aurelia: Aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-permission', (permissionStore: PermissionStore, configuration: Configuration) =>
      configurePermissions(aurelia, permissionStore, configuration));

  userPromise.then(() => {
    aurelia.start().then(() => aurelia.setRoot());
  });
}

function configurePermissions(aurelia: Aurelia, permissionStore: PermissionStore, configuration: Configuration) {
  configuration.useDefaultRedirectRoute('not-authorized');

  userPromise
    .then((user: any) => {
      permissionStore.useDefaultDefinition(user.permissions);
      permissionStore.definePermissionObject(UserPermission);

      return user;
    });
}

// And sample usage in route
 {
     route: 'users', name: 'users', moduleId: 'users', nav: true, title: 'Github Users',
     settings: {
     permission: {
        only: ['List_Users'],
     }
}

// And sample usage in the HTML
<div permission="only: AddUsers">Can add users!</div>
<div permission="only: DeleteUsers">Can delete users!</div>
<div permission="only: AddUsers, DeleteUsers">Can add or delete users!</div>
<div permission="only: ListUsers">Can list users!</div>

<input type="text" permission="only: ListUsers, DeleteUsers; disable.bind: true">
```

According to your last note, this plugin was written entirely in TS and distribution package js files should contain source maps in the end of each file. Thanks to that, you can debug the code in the browser i.e. Chrome creating breakpoints in the TS files via source maps, but you still run js code in your app. What is more, in the design time you can use TS definitions that are also available. 

Thanks and take care,
Mat

**Comment by matik12** [comment]
@reggersusa any comment / info?

**Comment by reggersusa** [comment]
Thanks for writing. We are on holiday in the US and I am away from my computer. As I said, I followed your read.md file exactly so I would not deviate from it in any way. My first goal is to see it work with the sampleUser and to test setting a permission on one route and another on one button on another page.

As I described, I set a break point in your authorization service. I can see it entered with the permission set on the route when I visit that particular route. Also, I see it entered on the other page with the permission limit on the button. But in bot cases, I cannot see the permissions of the sampleUser because the code is TypeScript and I don't have the source map. Single stepping does not work properly.

But in both cases, authority is granted, which is not what I expect. Tomorrow, I can send you code snippets and maybe you will see something.

Thanks,
Bob Eggers

**Comment by matik12** [comment]
Ok, I understand what you want to achieve, but to be able to find what is the problem your case I need exact configuration and usage sample or some simple repro project to find the actual problem.

In the README file, there are described at least 2 or 3 possible plugin configurations and related usage scenarios, so maybe you mixed them and that is the case. To make sure I need to see the code, because as I mentioned I have tested plugin using configuration as above and worked without any problems. 

Whenever you have time to give me more details, we can get back to this topic and curry on.

BTW, I don't know you meant by 'I don't have source map'? Distribution package code comes with source maps inlined in the bottom of the js files as it is visible i.e. => [Authorize Service](https://github.com/matik12/aurelia-permission/blob/master/dist/amd/authorize-service.js) so when you debug the code in the browser you can set break points in TS code and check logic related to this plugin implementation. I just confirm that this works in my sample project, so don't really know what you are trying to do. Also you can set a break point in your function that describe if a user has particular permission and check what is going on - return result. This would be in your custom code - plain js. 

Thanks and have a good holiday,
Mat

**Comment by reggersusa** [comment]
Hel Mat,
First, let me thank you for your help! I really appreciate your help and your personal attention! I will summarize the implementation as best as I can.

In main.js, I have declared these:

```js
import { PermissionStore, Configuration } from 'aurelia-permission';

// sample data for permissions demo:
const sampleUser = { 
  id: 1, 
  permissions: [ 'agreement_open', 'agreement_search' ]
};

const userPromise = new Promise(resolve => { 
  // Simulate promise getting user data including permissions from API 
  setTimeout(() => resolve(sampleUser), 1000);
});

function configurePermissions(aurelia: Aurelia, permissionStore: PermissionStore, configuration: Configuration) { 
  configuration.useDefaultRedirectRoute('dashboard');

  userPromise .then((user: any) => {
    const allApplicationPermissions = [];

    permissionStore.definePermissions( allApplicationPermissions, 
       // simple custom definition, the same function for all permissions 
       // it only checks if particular permission is included in user's permissions array 
      // if permissions need to have different definitions, then use
      // permissionStore.definePermissions() method for each specific permission 
     (permission: string) => { 
      // console.log('Custom definition function'); 

      return user.permissions.includes(permission); 
   );
     
   return user; 
   });
}
```

Also in main.js, the aurelia configure() method registers various plugins as follows:export function configure(aurelia: Aurelia) {
    ...
 aurelia.use
 .standardConfiguration() // .developmentLogging() .plugin('aurelia-validation') .plugin('aurelia-dialog') .plugin('aurelia-authentication', (baseConfig) => { baseConfig.configure(authConfigSingleton); // Use our own http client to intercept token and refresh calls baseConfig.endpoint = new AtlasAuthHttpClient(); }) .plugin('aurelia-i18n', (instance) => { instance.i18next.use(XHR); instance.setup({ backend: { loadPath: `${appConfigSingleton.clientPath}/static/locale/{{lng}}/{{ns}}.json` }, lng: appConfigSingleton.defaultLanguageSubtag, attributes: ['t', 'i18n'], getAsync: true, sendMissing: false, fallbackLng: 'en', debug: false }).then(() => { aurelia.setupI18NFinished = true; setRoot(aurelia); }); }) .plugin('aurelia-animator-css') .feature(`${appConfigSingleton.clientPath}/dist/tsd-library`)
 .plugin('aurelia-permission', (permissionStore: PermissionStore, configuration: Configuration) => configurePermissions(aurelia, permissionStore, configuration));
    ...
}


Then, I am testing 2 things: permission to navigate to a particular route and permission to display a page action button. First, the route table fragment:

```js
 { 
  route: 'agreement/:id', name: 'viewagreement', moduleId: 'components/agreements/agreement-view-page', title: 'view_agreement', 
  settings: { 
     permission: {only: ['agreement_view']}
  } 
},
```
And second, the fragment of HTML where I am trying to prevent a particular action button from displaying based on the persmissions:

```html
 <tsd-page-action permission="only: agreement_close" click.call="closeAgreement()" 
icon="agreement-close" text="close_agreement"></tsd-page-action>
```

In the first case, while sitting in the debugger in AuthorizeService.isAuthorized(), I see the request comes for the 'agreement_view' permission. I am not able to observe the user permissions, but the result of the isAuthorized function is true. In the second case, I see the request for the 'agreement_close' permission and the result is also true. In both cases, I expect that since the sampleUser permissions do not include either of these, the isAuthorized function should return false.
I am not able to observe the result of the getPermissionDefinitions() call or the following logic, because I do not have the source maps for the authorize-service.ts file. In that case, I might be better able to observe what is going wrong. But clearly, the permission definitions for the sampleUser are not being applied. Logic tells me so.
I tried adding console.log statements to the AuthorizeService.isAuthorized() method, but my changes are not reflected into the TypeScript in the next debug session.
Any assistance you can give to help me debug this would be greatly appreciated!
Bob

**Comment by matik12** [comment]
Hi @reggersusa,

I tried to format you response a little bit to see code configuration, because it is not readable at all .

What I can see so far is that, you define no permissions at all because your variable **allApplicationPermissions** is an empty array. This should be changed to list all possible supported permissions used in app i.e. 
```js
// sample from README file
const allApplicationPermissions = ['addUsers', 'deleteUsers', 'listUsers'];

// your use case
const allApplicationPermissions = [ 'agreement_open', 'agreement_search', 'agreement_view', 'agreement_close'];
```
Now we define 4 permissions and your sample user has only 2 of them, so he should be able to access everything secured only with  'agreement_open' or 'agreement_search' permission.
```js
const sampleUser = {
  id: 1,
  permissions: [ 'agreement_open', 'agreement_search' ]
};
```
This should help to secure your route and hide HTML elements properly. 

Again you are saying something about the source maps, you should have the source maps inlined in your js files installed via i.e. NPM. I mentioned this in the last response pointing you to the distribution file with source maps generated inside of it.

If you want to add custom code i.e. console.log for debugging purposes always do it in the js files related to this package npm/aurelia-permission/... and then refresh the app - your changes will stay untouched in the js file and you will be able to see the results.

Thanks and take care,
Mat

**Comment by reggersusa** [comment]
Aha, thank you. I clearly did not understand the purpose of this array.
Bob Eggers
