### ISSUE TITLE
Feature Suggestion: Tie Nav to permission

### ISSUE THREAD

**Issue by jonathanmilley** [matik12/aurelia-permission#2]
I'm looking at using your module in my application, and have a feature suggestion, right now assigning a permission setting to a route will prevent a user from accessing it (and redirecting them to a permission denied page) however when using the router.navigation property to drive a menu, that menu will show the items even if the user is not permitted.  It seems the suggested way is to do a second permission check for the route:  

```
{ route: 'child-router',  name: 'child-router', moduleId: 'child/child-router', nav: this.authorizationService.isAuthorized('ViewChildRouter'), title: 'Child Router', settings: {
          permission: {
            only: ['ViewChildRouter']
          }
        } },

```

It would be good if there was a default configuration item to say 
`configuration.trimNavigationWithPermission = true;`

Just getting started with Aurelia and not sure how easy/possible this would be to achieve.

**Comment by matik12** [comment]
Hi @jonathanmilley,

thanks for checking out my plugin.
You're right currently you need to add custom logic for dynamic menu items, which will set nav value according to proper permission values. 
My intention was to provide working plugin version with minimal feature set first, so you have **isAuthorized** method to do whatever you need and implement custom logic such as hiding nav menu items. 

Also it depends on the use case, because not everyone needs / wants to generate menu items dynamically (in most cases it is easier to manually manipulate menu items then generate it), so in manual case you have custom attribute  **permission** for this purpose to use in html and you're ok :)

In dynamic menu case, I can create **PermissionFilterValueConverter** that will filter out menu items based on settings.permission.only property, so you could use in the template where you generate your menu items like below. You will still need to set nav to true, if you want to show your menu item, but required permissions will be defined only in place.

```html
<li repeat.for="navigationItem of router.navigation | permissionFilter">...
```

I am not sure, if filtering menu items internally in plugin configuration could be achieved, because router manages mapped routes internally and you can only iterate navigation routes via router.navigation property. So far, I feel that value converter is a better option to go giving you flexibility and you can apply it on child routers as well. 

Btw, next time don't hesitate and implement an improvement in PR, so then we can merge it the master branch. Currently, I don't have too much free time to develop this plugin extensively. 

Thanks,
Mat

**Comment by matik12** [comment]
Hi @jonathanmilley,

As I mentioned above I implemented **PermissionFilterValueConverter** and released new plugin version. You can find more info in the README.

Thanks and take care,
Mat

**Comment by jonathanmilley** [comment]
This works great.  Thanks Mat, hopefully I'll be able to contribute back to the project in the future.

Jonathan
